### ISSUE TITLE
Support for multiarch container images

### ISSUE THREAD

**Issue by sxd** [alexellis/hey#1]
Hi @alexellis !!

Are you planning to support multiarch container images for testing purposes?

Thanks!

**Comment by alexellis** [comment]
There are no container images for hey, but 'arkade get hey' is multi arch 

Perhaps you can explain what you need and why a little better?

**Comment by sxd** [comment]
No need, it was easier to replace hey using Apache Benchmark, almost same arguments but without the lack of multi-arch.

I was needing a multiarch to run the CloudNativePG E2E in arm/arm64, but Apache Benchmark did the work =)

I'm closing this now! Thanks for your reply!
